name: C/C++ Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup_build_dir
      run: mkdir buildproducts
    - name: cmake
      working-directory: ./buildproducts
      run: cmake ..
    - name: make
      working-directory: ./buildproducts
      run: make
    - name: find
      working-directory: ./buildproducts
      run: find .
